# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.PositiveSmallIntegerField(null=True)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Group A'), (2, 'Group B'), (3, 'Group C')])),
            ],
        ),
    ]
