# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-04 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20180104_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmember',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
