# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-16 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20180215_2138'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='emailmember',
            index_together=set([('group',)]),
        ),
    ]
