# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-16 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20180216_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmember',
            name='name',
        ),
        migrations.AddField(
            model_name='emailmember',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmember',
            name='first_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=15),
        ),
        migrations.AddField(
            model_name='emailmember',
            name='language',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='emailmember',
            name='last_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
