# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-16 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0014_auto_20180216_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
