# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20180216_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmember',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=15, null=True),
        ),
    ]
