# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171127_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
