# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
    ]
