# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
