# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='page_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
