# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20171127_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
