# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
