# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0004_sendemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sendsms',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
