# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0005_auto_20171211_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendemail',
            old_name='email',
            new_name='recipients',
        ),
        migrations.AddField(
            model_name='sendemail',
            name='sender',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sendemail',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
