# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0006_auto_20171212_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='recipients',
            field=models.CharField(max_length=500),
        ),
    ]
