# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0007_auto_20180103_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='activity_list',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
