# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20180102_1054'),
        ('sendsms', '0008_sendsms_activity_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendsms',
            name='recipient_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='contacts.ContactGroup'),
        ),
    ]
