# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0010_auto_20180103_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='recipient_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
