# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0011_auto_20180103_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='recipient_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
