# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-04 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0013_sendemail_activity_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='recipients',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
