# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20180104_1701'),
        ('sendsms', '0014_auto_20180104_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='recipient_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='contacts.EmailGroup'),
        ),
    ]
