# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0017_auto_20180221_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendsms',
            old_name='recepient_group',
            new_name='recipient_group',
        ),
    ]
