# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20180221_1954'),
        ('sendsms', '0020_auto_20180221_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendemail',
            name='recipient_group',
        ),
        migrations.AddField(
            model_name='sendemail',
            name='recipient_group',
            field=models.ManyToManyField(blank=True, related_name='sent_emails', to='contacts.EmailGroup'),
        ),
    ]
