# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendsms', '0021_auto_20180221_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendsms',
            name='recipient_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='sent_sms', to='contacts.EmailGroup'),
        ),
    ]
