# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('activity_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('time_zone', timezone_field.fields.TimeZoneField(default='Australia/Melbourne')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
