# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20171204_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_time',
        ),
    ]
