# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20171204_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
