# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20171204_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
    ]
