# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
