# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20171206_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
