# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
