# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20171214_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydraft',
            name='term',
            field=models.CharField(blank=True, choices=[('Once', 'Only once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], default='Once', max_length=50),
        ),
    ]
