# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 04:53
from __future__ import unicode_literals

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0019_auto_20171214_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='term',
            field=models.CharField(blank=True, choices=[('Once', 'Only once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly'), ('Monthly', 'Monthly')], default='Once', max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_img',
            field=models.ImageField(blank=True, null=True, upload_to=activities.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='flyer',
            field=models.FileField(blank=True, null=True, upload_to=activities.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organiser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='activity_img',
            field=models.ImageField(blank=True, null=True, upload_to=activities.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='flyer',
            field=models.FileField(blank=True, null=True, upload_to=activities.models.file_directory_path),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='organiser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
