# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20171215_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydraft',
            name='listing_privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public Page: Accessible by anyone on Youthposter'), ('Private', 'Private Page: Accesible by only people you specify')], default='Public', max_length=50),
        ),
    ]
