# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_activitydraft_listing_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='background',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Only females'), ('M', 'Only males'), ('B', 'Both')], default='F', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='listing_privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public Page: Accessible by anyone on Youthposter'), ('Private', 'Private Page: Accesible by only people you specify')], default='Public', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='living_duration',
            field=models.CharField(blank=True, choices=[('Less', 'Less than 5 years'), ('More', 'More than 5 years'), ('Open', 'Open')], default='Less', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='space',
            field=models.PositiveSmallIntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Sports', 'Sports'), ('Fun', 'Fun'), ('Learn', 'Learn'), ('Job', 'Get a job'), ('Culture', 'Culture')], default='Sports', max_length=100),
        ),
    ]
