# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_auto_20171215_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='activitydraft',
            name='activity_type',
        ),
    ]
