# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_auto_20171218_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost_choice',
            field=models.CharField(choices=[('N', 'Free'), ('Y', 'Paid')], default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='space_choice',
            field=models.CharField(choices=[('Limited', 'Limited'), ('Unlimited', 'Unlimited')], default='Limited', max_length=50),
        ),
        migrations.AddField(
            model_name='activitydraft',
            name='cost_choice',
            field=models.CharField(choices=[('N', 'Free'), ('Y', 'Paid')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='gender',
            field=models.CharField(choices=[('F', 'Only females'), ('M', 'Only males'), ('B', 'Both')], default='F', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='listing_privacy',
            field=models.CharField(choices=[('Public', 'Public Page: Accessible by anyone on Youthposter'), ('Private', 'Private Page: Accesible by only people you specify')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='living_duration',
            field=models.CharField(choices=[('Less', 'Less than 5 years'), ('More', 'More than 5 years'), ('Open', 'Open')], default='Less', max_length=50),
        ),
    ]
