# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0028_auto_20171218_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydraft',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL),
        ),
    ]
