# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_activitydraft_published_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitydraft',
            name='published_ready',
        ),
    ]
