# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0033_auto_20171219_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydraft',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
