# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0034_auto_20171231_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
