# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-02 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0035_activity_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='bookmarked_users',
            field=models.ManyToManyField(related_name='bookmarked_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
