# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0036_activity_bookmarked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
