# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0038_auto_20180128_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='space',
            field=models.PositiveSmallIntegerField(blank=True, default=10, null=True),
        ),
    ]
