# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0039_auto_20180201_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
