# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0040_activity_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Fun', 'Fun'), ('Learn', 'Learn'), ('Job', 'Get a job'), ('Culture', 'Culture')], default='Sport', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Fun', 'Fun'), ('Learn', 'Learn'), ('Job', 'Get a job'), ('Culture', 'Culture')], default='Sports', max_length=100),
        ),
    ]
