# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-23 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0045_auto_20180216_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='listing_privacy',
        ),
        migrations.RemoveField(
            model_name='activitydraft',
            name='listing_privacy',
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activitydraft',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
