# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0047_auto_20180302_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='contact_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='activity',
            name='organiser',
            field=models.CharField(default='', max_length=150),
        ),
    ]
