branch-defaults:
  master:
    environment: active-brimbank-dev
environment-defaults:
  active-brimbank-dev:
    branch: null
    repository: null
global:
  application_name: active_brimbank
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
