# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180201_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_limit',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sms_limit',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
