# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180201_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recharged',
            field=models.BooleanField(default=True),
        ),
    ]
