# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_last_recharged'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_limit', models.PositiveSmallIntegerField(default=30)),
                ('email_limit', models.PositiveSmallIntegerField(default=30)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
