# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 23:47
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_adminemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organisation_logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.image_directory_path),
        ),
    ]
