# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-31 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180131_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='language',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
