# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20180131_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='activities.Activity'),
        ),
    ]
