# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-01 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20180216_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
